const ALARM_STATUS_TEXT = '알림';
const FEED_TEXT = '피드';
const FRIEND_TEXT = '친구';
const HOMETOWN_TEXT = '출신';
const INTRODUCTION_TEXT = '소개';
const RESIDENCE_TEXT = '거주';

export {
  ALARM_STATUS_TEXT,
  FEED_TEXT,
  FRIEND_TEXT,
  HOMETOWN_TEXT,
  INTRODUCTION_TEXT,
  RESIDENCE_TEXT
};
